Toss the centroid dashboard code into mica
sot/mica pull request #236
Opened 2020-08-22 20:01 UTC by jeanconn

## Description

Toss the centroid dashboard code into mica

## Testing

- [x] Has no unit tests
- [x] Functional testing - makes pages 

Fixes #

2020-09-30 15:02 UTC, taldcroft requested changes
Still not using code linting in the editor?  :smile:

2020-09-30 15:02 UTC, taldcroft commented on scripts/update_centroid_reports.py
> +import os
Unused imports.

2020-10-01 15:05 UTC, jeanconn commented
Haha.  Yeah, quickly edited these with emacs on the system from copies of the other bad scripts ... and removed options and such that used these imports without rechecking.

2020-10-09 12:28 UTC, taldcroft approved these changes

2020-10-09 15:23 UTC, merged